// -----------------------------------------------------------------------------
// File        : sram_1rw.v
// Description : Generic single-port synchronous SRAM macro wrapper.
//               Portability wrapper for ASIC/FPGA targets.
// -----------------------------------------------------------------------------
// ASIC_TARGET Note:
// When compiling for an ASIC implementation, this behavioral wrapper is typically
// replaced by a compiled SRAM macro generated by a memory compiler.
// -----------------------------------------------------------------------------

module sram_1rw #(
    parameter DATA_WIDTH = 8,
    parameter DEPTH      = 1024,
    parameter ADDR_WIDTH = 10
) (
    input  wire                  clk,
    input  wire                  rst_n,
    input  wire                  cs_n,
    input  wire                  we_n,
    input  wire [ADDR_WIDTH-1:0] addr,
    input  wire [DATA_WIDTH-1:0] wdata,
    output reg  [DATA_WIDTH-1:0] rdata
);

    // Memory array declaration
`ifdef FPGA_TARGET
    (* ram_style = "block" *) reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
`else
    reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
`endif

    // Synchronous Write and Read
    always @(posedge clk) begin
        if (!rst_n) begin
            rdata <= {DATA_WIDTH{1'b0}};
        end else if (!cs_n) begin
            if (!we_n) begin
                // Write operation
                mem[addr] <= wdata;
            end else begin
                // Read operation
                rdata <= mem[addr];
            end
        end
    end

endmodule
