// -----------------------------------------------------------------------------
// File        : sram_2rw.v
// Description : Generic dual-port synchronous SRAM macro wrapper.
//               1 write port, 1 read port (simple dual port).
//               Portability wrapper for ASIC/FPGA targets.
// -----------------------------------------------------------------------------
// ASIC_TARGET Note:
// When compiling for an ASIC implementation, this behavioral wrapper is typically
// replaced by a compiled SRAM macro generated by a memory compiler.
// -----------------------------------------------------------------------------

module sram_2rw #(
    parameter DATA_WIDTH = 8,
    parameter DEPTH      = 1024,
    parameter ADDR_WIDTH = 10
) (
    input  wire                  clk,
    input  wire                  rst_n,
    // Write Port
    input  wire                  we_n,
    input  wire [ADDR_WIDTH-1:0] waddr,
    input  wire [DATA_WIDTH-1:0] wdata,
    // Read Port
    input  wire                  re_n,
    input  wire [ADDR_WIDTH-1:0] raddr,
    output reg  [DATA_WIDTH-1:0] rdata
);

    // Memory array declaration
`ifdef FPGA_TARGET
    (* ram_style = "block" *) reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
`else
    reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
`endif

    // Synchronous Write
    always @(posedge clk) begin
        if (!we_n) begin
            mem[waddr] <= wdata;
        end
    end

    // Synchronous Read
    always @(posedge clk) begin
        if (!rst_n) begin
            rdata <= {DATA_WIDTH{1'b0}};
        end else if (!re_n) begin
            rdata <= mem[raddr];
        end
    end

endmodule
