# Zynq Block Design Generator (Live HDMI Architecture)
# Target: PYNQ-Z2 (xc7z020clg400-1)
# Project: npu200jb

set project_name "npu200jb"
set project_dir "[file normalize {D:/Final year project/npu200jb}]"

# Create project
create_project ${project_name} ${project_dir} -part xc7z020clg400-1 -force

# Set board part (PYNQ-Z2) - Skipped due to missing board files
# set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]

# Set IP Repositories
set_property ip_repo_paths [list \
    "[file normalize {D:/Final year project/Shared/IP/digilent-vivado-library}]" \
    "[file normalize {D:/Final year project/IP/TinyNPU200}]" \
] [current_project]
update_ip_catalog

# Create Block Design
create_bd_design "npu_system"

# ==============================================================================
# 1. Zynq Processing System (PS7)
# ==============================================================================
create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:* ps7
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 -config {make_external "FIXED_IO, DDR" Master "Disable" Slave "Disable" }  [get_bd_cells ps7]

# Configure PS7 Clocks & Interrupts
set_property -dict [list \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {125} \
    CONFIG.PCW_EN_CLK1_PORT {1} \
    CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {200} \
    CONFIG.PCW_USE_S_AXI_HP0 {1} \
    CONFIG.PCW_USE_FABRIC_INTERRUPT {1} \
    CONFIG.PCW_IRQ_F2P_INTR {1} \
] [get_bd_cells ps7]

# ==============================================================================
# 2. TinyNPU200 IP
# ==============================================================================
create_bd_cell -type ip -vlnv ai.local:user:tinynpu_top:1.0 tinynpu_0

# ==============================================================================
# 3. HDMI RX (dvi2rgb) & TX (rgb2dvi)
# ==============================================================================
create_bd_cell -type ip -vlnv digilentinc.com:ip:dvi2rgb:* dvi2rgb_0
create_bd_cell -type ip -vlnv digilentinc.com:ip:rgb2dvi:* rgb2dvi_0

# Enable Edid in dvi2rgb and set TMDS clocks
set_property -dict [list CONFIG.kEmulateDDC {true} CONFIG.kRstActiveHigh {false}] [get_bd_cells dvi2rgb_0]
set_property -dict [list CONFIG.kRstActiveHigh {false}] [get_bd_cells rgb2dvi_0]

# Make external HDMI ports
make_bd_intf_pins_external  [get_bd_intf_pins dvi2rgb_0/TMDS]
set_property name TMDS_RX [get_bd_intf_ports TMDS_0]

make_bd_intf_pins_external  [get_bd_intf_pins rgb2dvi_0/TMDS]
set_property name TMDS_TX [get_bd_intf_ports TMDS_0]

make_bd_intf_pins_external  [get_bd_intf_pins dvi2rgb_0/DDC]
set_property name DDC_RX [get_bd_intf_ports DDC_0]

# ==============================================================================
# 4. Video to AXI-Stream Converters
# ==============================================================================
create_bd_cell -type ip -vlnv xilinx.com:ip:v_vid_in_axi4s:* vid_in
create_bd_cell -type ip -vlnv xilinx.com:ip:v_axi4s_vid_out:* vid_out


# Configure video formats (RGB 24-bit)
set_property -dict [list CONFIG.C_PIXELS_PER_CLOCK {1} CONFIG.C_HAS_ASYNC_CLK {1}] [get_bd_cells vid_in]
set_property -dict [list CONFIG.C_PIXELS_PER_CLOCK {1} CONFIG.C_HAS_ASYNC_CLK {1}] [get_bd_cells vid_out]

# Connect DVI2RGB -> Video In -> NPU
connect_bd_intf_net [get_bd_intf_pins dvi2rgb_0/RGB] [get_bd_intf_pins vid_in/vid_io_in]
connect_bd_net [get_bd_pins dvi2rgb_0/PixelClk] [get_bd_pins vid_in/vid_io_in_clk]
connect_bd_net [get_bd_pins dvi2rgb_0/aPixelClkLckd] [get_bd_pins vid_in/vid_io_in_ce]
connect_bd_net [get_bd_pins dvi2rgb_0/aPixelClkLckd] [get_bd_pins vid_in/vid_io_in_reset]

connect_bd_intf_net [get_bd_intf_pins vid_in/video_out] [get_bd_intf_pins tinynpu_0/s_axis]

# Connect NPU -> Video Out -> RGB2DVI
connect_bd_intf_net [get_bd_intf_pins tinynpu_0/m_axis] [get_bd_intf_pins vid_out/video_in]
connect_bd_intf_net [get_bd_intf_pins vid_out/vid_io_out] [get_bd_intf_pins rgb2dvi_0/RGB]

connect_bd_net [get_bd_pins dvi2rgb_0/PixelClk] [get_bd_pins vid_out/vid_io_out_clk]
connect_bd_net [get_bd_pins dvi2rgb_0/PixelClk] [get_bd_pins rgb2dvi_0/PixelClk]
connect_bd_net [get_bd_pins dvi2rgb_0/aPixelClkLckd] [get_bd_pins vid_out/vid_io_out_ce]

# VTC Connection (recreate syncs for HDMI out based on timing generated by HDMI in)
create_bd_cell -type ip -vlnv xilinx.com:ip:v_tc:* vtc
set_property -dict [list CONFIG.enable_detection {true} CONFIG.enable_generation {true}] [get_bd_cells vtc]
connect_bd_intf_net [get_bd_intf_pins vid_in/vtiming_out] [get_bd_intf_pins vtc/vtiming_in]
connect_bd_intf_net [get_bd_intf_pins vtc/vtiming_out] [get_bd_intf_pins vid_out/vtiming_in]
connect_bd_net [get_bd_pins dvi2rgb_0/PixelClk] [get_bd_pins vtc/clk]

# ==============================================================================
# 5. AXI-Lite and AXI-Master (Memory) Automation
# ==============================================================================
# Connect NPU AXI-Lite to PS7 M_AXI_GP0
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config { Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/ps7/M_AXI_GP0} Slave {/tinynpu_0/s_axi} intc_ip {New AXI Interconnect} master_apm {0}}  [get_bd_intf_pins tinynpu_0/s_axi]

# Connect NPU AXI-Master (DMA) to PS7 S_AXI_HP0 (DDR Memory Access)
apply_bd_automation -rule xilinx.com:bd_rule:axi4 -config { Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} Master {/tinynpu_0/m_axi} Slave {/ps7/S_AXI_HP0} intc_ip {New AXI Interconnect} master_apm {0}}  [get_bd_intf_pins ps7/S_AXI_HP0]

# Connect clocks to video components
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins vid_in/aclk]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins vid_out/aclk]
connect_bd_net [get_bd_pins ps7/FCLK_CLK0] [get_bd_pins vtc/s_axi_aclk]
connect_bd_net [get_bd_pins ps7/FCLK_CLK1] [get_bd_pins dvi2rgb_0/RefClk]

# Re-route the interrupt
connect_bd_net [get_bd_pins tinynpu_0/interrupt] [get_bd_pins ps7/IRQ_F2P]

connect_bd_net [get_bd_pins tinynpu_0/rst_n] [get_bd_pins ps7/FCLK_RESET0_N]
connect_bd_net [get_bd_pins tinynpu_0/vid_locked_in] [get_bd_pins dvi2rgb_0/aPixelClkLckd]

# ==============================================================================
# 6. Generate Wrapper
# ==============================================================================
validate_bd_design
set wrapper_file [make_wrapper -files [get_files *.bd] -top]
add_files -norecurse [list $wrapper_file]
update_compile_order -fileset sources_1
set_property top npu_system_wrapper [current_fileset]
set_property top npu_system_wrapper [current_fileset]

puts "============================================================"
puts " SUCCESS: Block Design npu_system generated successfully!"
puts "============================================================"
