#include "cnn_int8.h"

// ---------------------------------------------------------
// EXTERN WEIGHTS (These will come from the weights.h file 
// generated by your Python script later, locked in Flash)
// ---------------------------------------------------------
extern const int8_t layer_0_weights[]; // Conv1 (3x3x1x4)
extern const int8_t layer_0_biases[];
extern const int8_t layer_2_weights[]; // Conv2 (3x3x4x8)
extern const int8_t layer_2_biases[];
extern const int8_t layer_5_weights[]; // Dense1 (384x16)
extern const int8_t layer_5_biases[];
extern const int8_t layer_6_weights[]; // Dense2 (16x3)
extern const int8_t layer_6_biases[];

// ---------------------------------------------------------
// FAST MAC MACRO (Utilizing RV32IM Hardware Multiply)
// ---------------------------------------------------------
#define INT8_MAC(acc, a, b) do { \
    acc += (int32_t)(a) * (int32_t)(b); \
} while(0)

// ---------------------------------------------------------
// NEURAL NETWORK LAYERS (Optimized for Bare-Metal C)
// ---------------------------------------------------------

// 2D Convolution (3x3 Kernel, SAME padding, ReLU activation)
void conv2d_3x3_int8(const int8_t* input, int8_t* output, int width, int height, int in_channels, int out_channels, const int8_t* weights, const int8_t* biases) {
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            for (int oc = 0; oc < out_channels; oc++) {
                int32_t acc = biases[oc]; // Initialize accumulator with bias
                
                // 3x3 Kernel window
                for (int ky = -1; ky <= 1; ky++) {
                    for (int kx = -1; kx <= 1; kx++) {
                        int iy = y + ky;
                        int ix = x + kx;
                        
                        // Zero padding check
                        if (iy >= 0 && iy < height && ix >= 0 && ix < width) {
                            for (int ic = 0; ic < in_channels; ic++) {
                                int in_idx = (iy * width * in_channels) + (ix * in_channels) + ic;
                                int w_idx = ((ky+1) * 3 * in_channels * out_channels) + ((kx+1) * in_channels * out_channels) + (ic * out_channels) + oc;
                                
                                INT8_MAC(acc, input[in_idx], weights[w_idx]);
                            }
                        }
                    }
                }
                
                // Right shift scaling (Quantization step - adjustable based on model)
                acc = acc >> 6; 
                
                // ReLU Activation
                if (acc < 0) acc = 0;
                // Clip to INT8
                if (acc > 127) acc = 127;
                
                output[(y * width * out_channels) + (x * out_channels) + oc] = (int8_t)acc;
            }
        }
    }
}

// 2x2 Max Pooling
void maxpool2d_2x2_int8(const int8_t* input, int8_t* output, int width, int height, int channels) {
    int out_w = width / 2;
    int out_h = height / 2;
    
    for (int y = 0; y < out_h; y++) {
        for (int x = 0; x < out_w; x++) {
            for (int c = 0; c < channels; c++) {
                int8_t max_val = -128;
                for (int ky = 0; ky < 2; ky++) {
                    for (int kx = 0; kx < 2; kx++) {
                        int iy = (y * 2) + ky;
                        int ix = (x * 2) + kx;
                        int in_idx = (iy * width * channels) + (ix * channels) + c;
                        if (input[in_idx] > max_val) {
                            max_val = input[in_idx];
                        }
                    }
                }
                output[(y * out_w * channels) + (x * channels) + c] = max_val;
            }
        }
    }
}

// Dense (Fully Connected) Layer with ReLU
void dense_int8(const int8_t* input, int8_t* output, int in_nodes, int out_nodes, const int8_t* weights, const int8_t* biases) {
    for (int o = 0; o < out_nodes; o++) {
        int32_t acc = biases[o];
        for (int i = 0; i < in_nodes; i++) {
            INT8_MAC(acc, input[i], weights[(i * out_nodes) + o]);
        }
        
        acc = acc >> 6; // Quantization scaling
        
        // ReLU Activation
        if (acc < 0) acc = 0;
        if (acc > 127) acc = 127;
        
        output[o] = (int8_t)acc;
    }
}

// ---------------------------------------------------------
// MAIN INFERENCE PIPELINE
// ---------------------------------------------------------

int8_t cnn_inference_int8(int32_t *thermal_q20_input) {
    // Memory efficient buffer ping-ponging (Fits well within SRAM limits)
    int8_t buffer_A[32 * 24 * 4]; // Max size needed for Conv1 output (3KB)
    int8_t buffer_B[16 * 12 * 8]; // Max size needed for Conv2 output (1.5KB)
    
    // 1. Quantize Input (Q20 Thermal Data -> INT8 Grayscale -128 to 127)
    for(int i=0; i<768; i++) {
        buffer_B[i] = (int8_t)((thermal_q20_input[i] - 18874368) >> 15); 
    }
    
    // 2. Inference Pass
    // Conv1: Input 32x24x1 -> Output 32x24x4
    conv2d_3x3_int8(buffer_B, buffer_A, 32, 24, 1, 4, layer_0_weights, layer_0_biases);
    
    // Pool1: Input 32x24x4 -> Output 16x12x4
    maxpool2d_2x2_int8(buffer_A, buffer_B, 32, 24, 4);
    
    // Conv2: Input 16x12x4 -> Output 16x12x8
    conv2d_3x3_int8(buffer_B, buffer_A, 16, 12, 4, 8, layer_2_weights, layer_2_biases);
    
    // Pool2: Input 16x12x8 -> Output 8x6x8 (Flattened size = 384)
    maxpool2d_2x2_int8(buffer_A, buffer_B, 16, 12, 8);
    
    // Dense1: Input 384 -> Output 16
    dense_int8(buffer_B, buffer_A, 384, 16, layer_5_weights, layer_5_biases);
    
    // Dense2 (Output): Input 16 -> Output 3 classes
    dense_int8(buffer_A, buffer_B, 16, 3, layer_6_weights, layer_6_biases);
    
    // 3. Find Argmax (Prediction)
    int8_t max_score = -128;
    int8_t predicted_class = 0;
    
    for (int i = 0; i < 3; i++) {
        if (buffer_B[i] > max_score) {
            max_score = buffer_B[i];
            predicted_class = (int8_t)i;
        }
    }
    
    // Returns: 0 (Non-Threat), 1 (Human), 2 (Vehicle)
    return predicted_class; 
}
