import tensorflow as tf
import numpy as np
import os

print("Building VEDA KAAVALAN Micro-CNN...")

# 1. Define the Micro-CNN Architecture
# Input is 24 height x 32 width x 1 channel (Grayscale Thermal)
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(24, 32, 1)),
    
    # Layer 1: Extract basic heat blobs
    tf.keras.layers.Conv2D(8, (3, 3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    
    # Layer 2: Extract shapes (Standing vs Fallen)
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    
    # Flatten and Classify
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(4, activation='softmax') # 4 Classes: Empty, Human, Fall, Vehicle
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print("Model architecture built. Training with dummy initialization data...")
# (In a real scenario, you'd load your thermal images here. 
# We use dummy data just to initialize the math graph for export).
dummy_x = np.random.rand(100, 24, 32, 1).astype(np.float32)
dummy_y = np.random.randint(0, 4, size=(100,))
model.fit(dummy_x, dummy_y, epochs=1, verbose=0)

# 2. INT8 Quantization (The Magic for VEGA NO-FPU constraint)
print("Quantizing model to INT8...")
def representative_dataset():
    for i in range(100):
        yield [dummy_x[i:i+1]]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # Force INT8 Input
converter.inference_output_type = tf.int8 # Force INT8 Output

tflite_quant_model = converter.convert()

# 3. Export to a C Header file
header_file = "cnn_weights.h"
print(f"Exporting weights to C-array: {header_file}...")

hex_array = [format(b, '#04x') for b in tflite_quant_model]
c_str = "// Automatically generated by train_and_export.py\n"
c_str += "// VEDA KAAVALAN Micro-CNN (Full INT8 Quantized)\n"
c_str += f"// Model Size: {len(tflite_quant_model)} bytes\n"
c_str += "// Target: VEGA ET1031 RISC-V (.rodata mapping)\n\n"
c_str += "#ifndef CNN_WEIGHTS_H\n#define CNN_WEIGHTS_H\n\n"
c_str += "const unsigned char veda_cnn_weights[] = {\n  "

for i, hex_val in enumerate(hex_array):
    c_str += f"{hex_val}, "
    if (i + 1) % 12 == 0:
        c_str += "\n  "
        
c_str += "\n};\n\n"
c_str += f"const unsigned int veda_cnn_weights_len = {len(tflite_quant_model)};\n\n"
c_str += "#endif // CNN_WEIGHTS_H\n"

with open(header_file, "w") as f:
    f.write(c_str)

print("--------------------------------------------------")
print(f"SUCCESS! AI Model compressed to {len(tflite_quant_model)} bytes.")
print(f"File '{header_file}' is ready to be included in your VEGA C firmware.")
print("--------------------------------------------------")
