import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' # Hide TF warnings
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models

print("[+] VEDA KAAVALAN - Micro-CNN Training Pipeline")

# 1. Generate Synthetic Dataset (Replace with your actual thermal data later)
# Input shape: (32, 24, 1) - corresponding to MLX90640 resolution
NUM_SAMPLES = 1000
print("[*] Generating synthetic 32x24 thermal dataset...")
X_train = np.random.rand(NUM_SAMPLES, 32, 24, 1).astype(np.float32)
# Classes: 0 (Non-Threat), 1 (Human), 2 (Vehicle)
y_train = np.random.randint(0, 3, size=(NUM_SAMPLES,))

# 2. Define Ultra-Lightweight Micro-CNN (~4k parameters to fit 100MHz VEGA)
model = models.Sequential([
    layers.InputLayer(input_shape=(32, 24, 1)),
    layers.Conv2D(4, (3, 3), activation='relu', padding='same'),
    layers.AveragePooling2D((2, 2)),
    layers.Conv2D(8, (3, 3), activation='relu', padding='same'),
    layers.AveragePooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(16, activation='relu'),
    layers.Dense(3, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print("[*] Training model (5 epochs)...")
model.fit(X_train, y_train, epochs=5, batch_size=32, verbose=1)

# 3. Quantize to INT8 using TFLite
print("[*] Quantizing model to INT8...")
def representative_dataset():
    for i in range(100):
        yield [X_train[i:i+1]]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_quant_model = converter.convert()

with open('thermal_cnn_int8.tflite', 'wb') as f:
    f.write(tflite_quant_model)
print("[+] INT8 Model saved as thermal_cnn_int8.tflite")

# 4. Extract Weights and Export to C Header (.h)
print("[*] Extracting INT8 weights to C header file for VEGA board...")
# For a hackathon, parsing the raw TFLite flatbuffer is tedious. 
# A clever shortcut: extract the quantized weights directly from the Keras layers 
# and scale them based on standard min/max ranges.
# Since we are writing a custom bare-metal inference loop in C, we just dump the raw arrays.

header_content = """#ifndef CNN_WEIGHTS_H
#define CNN_WEIGHTS_H
#include <stdint.h>

// VEDA KAAVALAN - Autogenerated INT8 Micro-CNN Weights
// These reside exclusively in the 2MB Flash memory via .rodata

"""

layer_idx = 0
for layer in model.layers:
    weights = layer.get_weights()
    if len(weights) > 0:
        w, b = weights
        # Rough INT8 quantization mapping (-128 to 127)
        w_scale = np.max(np.abs(w)) / 127.0
        w_int8 = np.clip(np.round(w / w_scale), -128, 127).astype(np.int8)
        
        b_scale = np.max(np.abs(b)) / 127.0 if np.max(np.abs(b)) > 0 else 1.0
        b_int8 = np.clip(np.round(b / b_scale), -128, 127).astype(np.int8)
        
        w_flat = w_int8.flatten()
        b_flat = b_int8.flatten()
        
        header_content += f"__attribute__((section(\".rodata\"))) const int8_t layer_{layer_idx}_weights[{len(w_flat)}] = {{"
        header_content += ", ".join(map(str, w_flat))
        header_content += "};\n\n"
        
        header_content += f"__attribute__((section(\".rodata\"))) const int8_t layer_{layer_idx}_biases[{len(b_flat)}] = {{"
        header_content += ", ".join(map(str, b_flat))
        header_content += "};\n\n"
        
        layer_idx += 1

header_content += "#endif // CNN_WEIGHTS_H\n"

with open('weights.h', 'w') as f:
    f.write(header_content)
    
print("[+] Successfully exported INT8 weights to weights.h!")
print("[+] Phase 1 AI Pipeline Complete. Ready to copy weights.h to VEGA Firmware.")
